name = "iyb-create-checkout"
main = "src/index.js"
compatibility_date = "2023-04-03"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

# The necessary secrets are:
# - STRIPE_SECRET_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these